postgresql:
  image: postgres:9.6
  ports:
    - 5432:5432
    - 80:80
  environment:
    - PGDATA=/postgresql
    - PG_PASSWORD=our-awesome-bookstore-app
  volumes:
    - ./tmp/data/postgresql:/postgresql
